apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: istudentapp
  name: mavenrepo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: istudentapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: istudentapp
    spec:
      containers:
      - image: arjundevsecops/mavenrepo:latest
        name: mavenrepo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: istudentapp
