apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: studentapp
  name: studentapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: studentapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: studentapp
    spec:
      containers:
      - image: arjundevsecops/mavenrepo:44
        name: studentapp
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: studentapp
